// genie-app/static/genie-ts/src/App.tsx
import React, { useEffect, useState } from 'react';
import { invoke } from '@forge/bridge';

function App() {
    const [data, setData] = useState(null);

    useEffect(() => {
        // @ts-ignore
        invoke('getText', { example: 'my-invoke-variable' }).then(setData);
    }, []);

    return (
        <div>
            {data ? data : 'Loading...'}
        </div>
    );
}

export default App;

// genie-app/static/genie-ng/src/app/app.component.ts
import { Component } from '@angular/core';

import { invoke } from '@forge/bridge';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  loaded: boolean = false;
  result: string = "?";

  ngOnInit() {
    console.log("In init, invoking...");
    invoke('getText', { example: 'my-invoke-variable' }).then(result => {
      console.log("Received invoke result", result);
      this.result = <string>result;
    });
  }
}


<div *ngIf="loaded">{{result}}</div>

<div *ngIf="! loaded">Loading...</div>

<router-outlet></router-outlet>
